server {
    listen 80;
    server_name tools.schatzsuche40.de;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/aktien-tool2/aktien-tool.sock;
    }


    # Static files directly via Nginx for better performance
    location /static {
        alias /home/ubuntu/aktien-tool2/static;
    }

    location /output {
        alias /home/ubuntu/aktien-tool2/output;
    }
}
